version: '3.8'

services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EXTRA_PHP_LIBRARIES: "pdo_mysql gd intl"

    environment: #Override enviroment files
      - DB_CONNECTION=mysql
      - DB_HOST=laravel_db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_PORT=3306
      - APP_ENV=local
    volumes:
      - '.:/app'
    ports:
      - "5000:8000"
      - "5173:5173"
    entrypoint: ./entrypoint-dev.sh
    # command: ["-p", "8080", "-n", "14"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      retries: 3
      timeout: 5s
    depends_on:
      - db

  db:
    image: mariadb:latest
    hostname: laravel_db
    container_name: laravel_db
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MYSQL_DATABASE: laravel
      MYSQL_USER: app
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 3306
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "55274:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
        test: ["CMD", "mariadb-admin", "ping"]
        retries: 3
        timeout: 5s

volumes:
  db-data: